apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets-age.sops.yaml
  - secrets-ssh.sops.yaml
  - ../config/
  - flux-install.yaml
  - flux-repo.yaml
  - ../../../repos/helm/app-template/
  - ../../../deploy/core/_networking/cilium/
  - ../../../deploy/core/kyverno/_deps/
  - ../../../deploy/core/kyverno/
