apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: |
    # created: 2023-11-01T22:10:13+01:00
    # public key: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
    AGE-SECRET-KEY-1VULN6FEA9S7SJ8H42P7KF7QQC499HDZVH0HDQX8KR7F0JYCY6WEQM4DKTN
