apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crds-prometheus
spec:
  interval: 12h
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    tag: kube-prometheus-stack-51.10.0
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/charts/kube-prometheus-stack/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-prom-crds
  labels: # for my repo's Fluxtomization patching, can be ignored for those passing by
    substitution.flux.home.arpa/disabled: "true"
    prune.flux.home.arpa/disabled: "true"
spec:
  interval: 30m
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: crds-prometheus
