apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chart:
    spec:
      chart: grafana-operator
      version: v5.4.2
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
        namespace: flux-system
  interval: 1h
