apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage-big-data
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner/
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: big-data
      reclaimPolicy: Retain
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /mnt/big-data/pvc/
