apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: ${ACME_EMAIL}
    server: ${ISSUER_URL}
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - selector:
          dnsZones:
            - ${CLUSTER_DOMAIN}
        dns01:
          cloudflare:
            email: ${ACME_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "cert-manager=CLUSTER_DOMAIN_CERT" # Sync certificate to matching namespaces
  secretName: letsencrypt-wildcard-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "${CLUSTER_DOMAIN}"
    - "*.${CLUSTER_DOMAIN}"
