apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main
  namespace: monitoring
spec:
  retentionPeriod: "12"
  extraArgs:
    dedup.minScrapeInterval: 60s
  removePvcAfterDelete: false
  storage:
    accessModes:
      - ReadWriteOnce
    storageClassName: big-data
    resources:
      requests:
        storage: 1Ti
