---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crds-kyverno
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kyverno/kyverno.git
  ref:
    tag: "v1.10.4"
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/config/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-kyverno-crds
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "kyverno"
    kustomization.flux.home.arpa/default: "false"
    kustomization.flux.home.arpa/helmpatches: "false"
    substitution.flux.home.arpa/disabled: "true"
    prune.flux.home.arpa/disabled: "true"
spec:
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: crds-kyverno
