#cloud-config

package_update: true
package_upgrade: true

timezone: Europe/Paris

packages:
  - qemu-guest-agent
  - chrony

users:
  - name: sam
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$ZYfe6wn7kfS76yJN$UZTEkiaBshjtJQn8ILXOyar1UmerrE8fvK9bIikDDCaa/gGboJhqA.dp0pPBmngOeVft3DauzhJG.6nn/uPXF0"
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILCvVNpUhek74zv1yOnhYSvnIOWMJ6BMBK6AgDvYGp5R
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxT3VVL61Juhpl/ffT4HU7+DQfbEGOGlqRyqrSJQQNHRfferPK2IT2p+aY4+XtqgoW3uw5cecpMAFOYCcGBA3fOQfw10nEE+JUfbeIoFRhpl5c4m9kBHuAj3427ROP6u9YYNvPol2xhjWEWLoHPk8Pvm5SvJEOyLXJ9YRs2HM+9KWTwFmfPdTXKss86UvSPG2PBF/gUooiyaXHUGzDpEdcwEeexwjPm7L+RkB7Nm63L6id8Dwohzm/Idp89PbJ4WJgSKp3zDIAmu7/OZzaGxYf6p5Vrps3VQxatU6/JzRxVXj13Nx06pdv2XdEU/pcsCuVNdIH6Akm3X139L2tMvKL

fqdn: k3s1.home.lab

preProvision:
  - &disableIPV6 |
    echo "net.ipv6.conf.all.disable_ipv6 = 1" > /etc/sysctl.d/70-disable-ipv6.conf
    sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

runcmd:
  - [sh, -c, *disableIPV6]

power_state:
  delay: now
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
