apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: steropes-secrets
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:qjfxDc7fso4Zyr0=,iv:7FKAROVCnMCzgxOPbCjitRQDMFnAOnKuVML3QFgbsqA=,tag:CM/UK7MObv3L6uttlc61mg==,type:str]
  ACME_EMAIL: ENC[AES256_GCM,data:JqTqyxYHj76pz1TDtjuaWpAmnvJG,iv:81ppmEcJYv0uN+ipvR96dOgShpaGZKDrDJmM2HTQAS8=,tag:dUXP0NHGdAVKFO0+A6PHyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWjRWVXFXSUVOR2N5ZllP
        eG1MN05jM3B4WnlpTmNrWjVGcVQ2RXl3d1ZNCjZ6RW1jbzg3Zm0zaGR4V08vWk1w
        VmVzczJ4cnhBWUxVM1dpd0Q4RkVIamsKLS0tIDFKRmc5cDRXNXN1dkZ2TG5GTFVm
        aWYzODJ0RVNEcE9OTXJrMHdVVUMzdm8KgYjr6TCCcLIpNrAuwX6Hae2d4BlzRUQ4
        v3cya956I9vcTkLOPIC2O1FTs+dLo5eJlOUKidVZo4U4/31OXiMCpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-11-08T06:57:57Z"
  mac: ENC[AES256_GCM,data:BeGKDFpSWQNXVfeJgd+ZJEmJ1S4YO2EpKVLtsW2DS3yh/3EfaDLo2doFcM4A0JDSP8IfXiGuXVUBBTU83hKzbJAYS+uvHyu1/Wo+tRNQ2HDGbY/G9EXJTtS6xTbnoqH1jKBKAc+t+D9N04x7CZZLoeldo34dLIckuqTG99hyx6M=,iv:eXQnt24vMIrmHMEmbm/RGA8qjV3CKfO9eCKHXARQXKo=,tag:8luOrmmHk61RpqJcqcKo0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
