apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vm-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.27.4
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    operator:
      # -- By default, operator converts prometheus-operator objects.
      disable_prometheus_converter: true
    # -- Resources for operator
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 150Mi
