apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m5s
  dependsOn:
    - name: operators
  sourceRef:
    kind: GitRepository
    name: gitops-github-repo
  path: ./core
  prune: true
  #validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: global-settings
      - kind: Secret
        name: global-secrets
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
