apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
    values:
      kubeProxyReplacement: true
      k8sServiceHost: ${K3S_IP}
      k8sServicePort: ${K3S_PORT}
      clusterDomain: cluster
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
        peeerService:
          clusterDomain: cluster
      operator:
        replicas: 1
      localRedirectPolicy: true
      bgpControlPlane:
        enabled: true
      gatewayAPI:
        enabled: true
      envoy:
        enabled: true
      bpf:
        masquerade: true
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList: ${POD_CIDR}
          clusterPoolIPv4MaskSize: ${MASK_SIZE_PER_NODE}
